//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsccWebTeam.HouseStyle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EsccWebTeam.HouseStyle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ext.
        /// </summary>
        internal static string AbbrExtension {
            get {
                return ResourceManager.GetString("AbbrExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string AbbrFullExtension {
            get {
                return ResourceManager.GetString("AbbrFullExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string ContactPrefixSeparator {
            get {
                return ResourceManager.GetString("ContactPrefixSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe Acrobat (PDF) format.
        /// </summary>
        internal static string DownloadFormatPDF {
            get {
                return ResourceManager.GetString("DownloadFormatPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich Text format.
        /// </summary>
        internal static string DownloadFormatRTF {
            get {
                return ResourceManager.GetString("DownloadFormatRTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel format.
        /// </summary>
        internal static string DownloadFormatXLS {
            get {
                return ResourceManager.GetString("DownloadFormatXLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailPrefix {
            get {
                return ResourceManager.GetString("EmailPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string FaxPrefix {
            get {
                return ResourceManager.GetString("FaxPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See a map of this address.
        /// </summary>
        internal static string MapLinkText {
            get {
                return ResourceManager.GetString("MapLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string TelephonePrefix {
            get {
                return ResourceManager.GetString("TelephonePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit .
        /// </summary>
        internal static string WebsiteLeadIn {
            get {
                return ResourceManager.GetString("WebsiteLeadIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website: .
        /// </summary>
        internal static string WebsitePrefix {
            get {
                return ResourceManager.GetString("WebsitePrefix", resourceCulture);
            }
        }
    }
}
